#
#  .travis.yml
#
#  Copyright (c) 2014 Netguru Sp. z o.o. All rights reserved.
#

language: objective-c
osx_image: xcode6.1

xcode_workspace: SaasKit.xcworkspace
xcode_scheme: SaasKit
xcode_sdk: iphonesimulator8.0

before_install:
  - bundle install --without development --deployment --jobs=3 --retry=3

install:
  - bundle exec pod install --no-integrate

notifications:
  email: false
