#
#  .travis.yml
#
#  Copyright (c) 2014 Netguru Sp. z o.o. All rights reserved.
#
#  Currently, xctool is unable to build project with custom frameworks.
#  Until facebook/xctool#415 is fixed, we'll have to use xcpretty.
#

language: objective-c
osx_image: xcode6.1

env:
  global:
    - XCODE_WORKSPACE="Devise.xcworkspace"
    - XCODE_SCHEME="Devise"
    - XCODE_SDK="iphonesimulator8.1"

before_install:
  - bundle install --without development --deployment --jobs=3 --retry=3

install:
  - bundle exec rake install

before_script:
  - bundle exec rake review

script:
  - bundle exec rake test

notifications:
  email: false
  slack:
    secure: JCsk79VCfndQRBqz3P4xj1ydQRcQzqvcv9iXVlwIfMKCrf0/s+Z7ZN+KBmP7k05EyVyzyZEBX16V4KfNF9xd7gQLME/89lKLHqPd4PXsqF9fB9v40XhiqBRtO7CPzUzPHymmDlzkVT/U0kqBW5bvQ411Cv3n6VHoD8nO4OE0RZM=
