language: objective-c
osx_image: xcode6.1
env:
  global:
  - XCODE_WORKSPACE="Devise.xcworkspace"
  - XCODE_SCHEME="Devise"
  - XCODE_SDK="iphonesimulator8.1"
  - APPNAME="Devise Demo"
  - 'DEVELOPER_NAME="iPhone Distribution: netguru sp. z o. o. (SK8PDF7SG9)"'
  - PROFILE_UUID=94387ae1-1cb2-49fa-96df-c64bdede7ca1
  - secure: Hj3sIdUnu5AmOUXWGsyCjgzgV6nokr1UJCta7kITd4AWhttKlXasO8nrMmwjHx6Ry3Atoyym2yR1lBsjEEojFaK32gVFJoWOPipYv3COcHhl0gUC6RK6B+qnLI/bsXlggFQGG2rN5RlK/zfVoaiuPZueQC7yPCeg6tgsjFNuf5M=
  - secure: MAw9r7WseCfsTRITEG1zkr2sbrwcocDdLTskXXES/SKu+C7bLLQdc9m7+ub7cX6TSARRzeTmTSQepIBOhl0m9Q0W3XTL994JhyazB0aTsOPT4Nn3comJkg+kBsxRhTvbGx+p/pTqWryIC/XQDHVLkbGnm/NR5wtbhDCS1FeFYWc=
  - secure: P+AQUGqg6qijaQY9wLdPMboVlO+VAht4eD00bLkDoenp/w/hRoMFayWmn9pNYEQDQpB+JTSupAb4zRlMvcf7WW7ecGWMQcrpzxh58drPvmoFFpcEycSdfluY57aaeqvhr1x/a5bsE0F4NxckwJA7uAw/bWrS8ghzSqRN1PXcwqU=
before_install:
- bundle install --without development --deployment --jobs=3 --retry=3
- chmod +x scripts/travis/add-key.sh
- chmod +x scripts/travis/remove-key.sh
- chmod +x scripts/travis/testflight.sh
install:
- bundle exec rake install
before_script:
- bundle exec rake review
- ./scripts/travis/add-key.sh
script:
- bundle exec rake test
after_script:
- ./scripts/travis/remove-key.sh
after_success:
- ./scripts/travis/testflight.sh

notifications:
  email: false
  slack:
    secure: JCsk79VCfndQRBqz3P4xj1ydQRcQzqvcv9iXVlwIfMKCrf0/s+Z7ZN+KBmP7k05EyVyzyZEBX16V4KfNF9xd7gQLME/89lKLHqPd4PXsqF9fB9v40XhiqBRtO7CPzUzPHymmDlzkVT/U0kqBW5bvQ411Cv3n6VHoD8nO4OE0RZM=
