#
#  .travis.yml
#
#  Copyright (c) 2014 Netguru Sp. z o.o. All rights reserved.
#

language: objective-c
osx_image: xcode6.1

cache:
  directories:
    - vendor/bundle

env:
  global:
    - CERTS_DIR="Certificates"
    - 'CERT_NAME="iPhone Distribution: netguru sp. z o. o. (SK8PDF7SG9)"'
    - PROFILE_NAME="DeviseDemoDistribution.mobileprovision"
    - XCODE_INFOPLIST_PATH="Supporting Files/Devise-Demo-Info.plist"
    - XCODE_WORKSPACE="Devise.xcworkspace"
    - XCODE_SCHEME="Devise"
    - XCODE_SDK="iphonesimulator8.1"
    - TESTFLIGHT_LISTS="Devise"

matrix:
  include:
    - env: RAKE_SUITE=test
    - env: RAKE_SUITE=build-and-distribute

  fast_finish: true

before_install:
  - bundle config build.nokogiri --use-system-libraries
  - bundle install --without development --deployment --jobs=3 --retry=3

install:
  - bundle exec rake install

before_script:
  - bundle exec rake review

script:
  - bundle exec rake ${RAKE_SUITE}

notifications:
  email: false
  slack:
    secure: JCsk79VCfndQRBqz3P4xj1ydQRcQzqvcv9iXVlwIfMKCrf0/s+Z7ZN+KBmP7k05EyVyzyZEBX16V4KfNF9xd7gQLME/89lKLHqPd4PXsqF9fB9v40XhiqBRtO7CPzUzPHymmDlzkVT/U0kqBW5bvQ411Cv3n6VHoD8nO4OE0RZM=
